import java.io.Serializable;

public class dataSchema implements Serializable {

    /*
    "termstatistics.documentlength":36
    "filename":"app/210/patch/core/isv/java/src/core/mfpackage/development/PackageComponentsSpiderPatch.java2"
    "p4.action":"edit"
    "p4.change":"15030665"
    "p4.committer":"thoefner"
    "p4.reviewer":"benjamin.smith"
    "p4.date":"2017/12/15"
    "p4.time":"15:54:46"
    "p4.gusid":"a07B0000003tPH0"
    "p4.filecount":"15"
    "gus.worktype":"Bug"
    "fix.filename":"//app/210/patch/core/isv/java/src/core/mfpackage/development/PackageComponentsSpiderPatch.java#3"
    "fix.p4.gusid":"a07B0000003uT48"
    "fix.gus.worktype":"Bug"
    "fix.p4.change":"15236043"
    "p4.version":"2"
    "label":"1"
    "date.release":"210"
    "date.label":"r2a"
    "date.days":"63"
    "avgIdentifierLength":"10.88"
    "blockCount":"16"
    "fieldCount":"1"
    "termstatistics.termfrequency.lexer.types.field.boolean":1
    "termstatistics.docfrequency.lexer.types.field.boolean":13731
    "termstatistics.tfidf.lexer.types.field.boolean":1.4639567
    "termstatistics.termfrequency.lexer.types.local_variable.EntityCommon":1
    "termstatistics.docfrequency.lexer.types.local_variable.EntityCommon":3290
    "termstatistics.tfidf.lexer.types.local_variable.EntityCommon":3.2153466
    "termstatistics.termfrequency.lexer.types.local_variable.ManageableStateEnum":1
    "termstatistics.docfrequency.lexer.types.local_variable.ManageableStateEnum":283
    "termstatistics.tfidf.lexer.types.local_variable.ManageableStateEnum":7.802726
    "termstatistics.termfrequency.lexer.types.local_variable.boolean":2
    "termstatistics.docfrequency.lexer.types.local_variable.boolean":27615
    "termstatistics.tfidf.lexer.types.local_variable.boolean":1.2092816
    "termstatistics.termfrequency.lexer.types.method_signature.parameter.List":1
    "termstatistics.docfrequency.lexer.types.method_signature.parameter.List":20580
    "termstatistics.tfidf.lexer.types.method_signature.parameter.List":1.0914972
    "termstatistics.termfrequency.lexer.types.method_signature.parameter.List<PackageComponent>":1
    "termstatistics.docfrequency.lexer.types.method_signature.parameter.List<PackageComponent>":5
    "termstatistics.tfidf.lexer.types.method_signature.parameter.List<PackageComponent>":19.079748
    "termstatistics.termfrequency.lexer.types.method_signature.parameter.ManageableStateEnum":1
    "termstatistics.docfrequency.lexer.types.method_signature.parameter.ManageableStateEnum":332
    "termstatistics.tfidf.lexer.types.method_signature.parameter.ManageableStateEnum":7.443925
    "termstatistics.termfrequency.lexer.types.method_signature.parameter.Map":3
    "termstatistics.docfrequency.lexer.types.method_signature.parameter.Map":13737
    "termstatistics.tfidf.lexer.types.method_signature.parameter.Map":2.5349
    "termstatistics.termfrequency.lexer.types.method_signature.parameter.Map<String,ExtendedPackageInfo>":1
    "termstatistics.docfrequency.lexer.types.method_signature.parameter.Map<String,ExtendedPackageInfo>":5
    "termstatistics.tfidf.lexer.types.method_signature.parameter.Map<String,ExtendedPackageInfo>":19.079748
    "termstatistics.termfrequency.lexer.types.method_signature.parameter.Map<String,ManageableStateEnum>":1
    "termstatistics.docfrequency.lexer.types.method_signature.parameter.Map<String,ManageableStateEnum>":5
    "termstatistics.tfidf.lexer.types.method_signature.parameter.Map<String,ManageableStateEnum>":19.079748
    "termstatistics.termfrequency.lexer.types.method_signature.parameter.Map<String,VersionInfo>":1
    "termstatistics.docfrequency.lexer.types.method_signature.parameter.Map<String,VersionInfo>":5
    "termstatistics.tfidf.lexer.types.method_signature.parameter.Map<String,VersionInfo>":19.079748
    "termstatistics.termfrequency.lexer.types.method_signature.parameter.PackageMemberNode":5
    "termstatistics.docfrequency.lexer.types.method_signature.parameter.PackageMemberNode":6
    "termstatistics.tfidf.lexer.types.method_signature.parameter.PackageMemberNode":41.44314
    "termstatistics.termfrequency.lexer.types.method_signature.parameter.String":3
    "termstatistics.docfrequency.lexer.types.method_signature.parameter.String":74593
    "termstatistics.tfidf.lexer.types.method_signature.parameter.String":0.46663582
    "termstatistics.termfrequency.lexer.types.method_signature.parameter.boolean":7
    "termstatistics.docfrequency.lexer.types.method_signature.parameter.boolean":31678
    "termstatistics.tfidf.lexer.types.method_signature.parameter.boolean":1.9964776
    "termstatistics.termfrequency.lexer.types.method_signature.return_type.ImageElement":1
    "termstatistics.docfrequency.lexer.types.method_signature.return_type.ImageElement":31
    "termstatistics.tfidf.lexer.types.method_signature.return_type.ImageElement":13.576567
    "termstatistics.termfrequency.lexer.types.method_signature.return_type.boolean":6
    "termstatistics.docfrequency.lexer.types.method_signature.return_type.boolean":33031
    "termstatistics.tfidf.lexer.types.method_signature.return_type.boolean":1.7764322
    "maxBlockNestLevel":"3"
    "maxMethodLineCount":"22"
    "methodCount":"7"
    "tokenCount":"631"
    "variableCount":"25"
    "varsPerMethodCount":"3.57"}
    */
}
